name:                langtons-ant
version:             0.1.0.0
github:              "nitros12/langtons-ant"
license:             BSD3
author:              "Ben Simms"
maintainer:          "ben@bensimms.moe"
copyright:           "2018 Ben Simms"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nitros12/langtons-ant#readme>

dependencies:
- base >= 4.7 && < 5
- protolude >= 0.2.2
- mtl >= 2.2.2
- hashmap >= 1.3.3
- gloss >= 1.12
- gloss-rendering >= 1.12
- hashable >= 1.2.6
- lens >= 4.16
- data-default >= 0.7.1
- extra >= 1.6.6

library:
  source-dirs: src

default-extensions: NoImplicitPrelude

executables:
  langtons-ant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    dependencies:
    - langtons-ant

tests:
  langtons-ant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - langtons-ant
